<?php
  /**
   * @var $block \IWD\CartToQuote\Block\Customer\Quotes\Grid
   */
?>
<?php if ($block->isConnectionError()) : ?>
    <h1><?php echo __('Unable to Connect') ?></h1>
    <div>
        <p><?php echo __('We have some issue with connection to API Server.') ?></p>
        <p><?php echo __('Try to reload the page if it doesn\'t help please, let admin know about this issue.') ?></p>
        <p><?php echo __('Thank you for understanding.') ?></p>
    </div>
<?php else : ?>
    <iframe id='customerQuoteFrame' name='customerQuoteFrame' src='<?php echo $block->getGridUrl() ?>' scrolling="no"
            style="border:none; width:1px; *width:100%; min-width:100%; position:relative; frameborder:0; overflow:hidden; margin: -2px 0 0 -10px;">
        <?php __('Sorry, your browser does not support iframe') ?>
    </iframe>
    <div id="iwd_c2q_iframe_loader_wrapper" class="iwd_c2q_loader_wrapper">
        <div class="iwd_c2q_loader_mask"></div>
        <div class="iwd_c2q_loader"></div>
    </div>
    <script type="text/javascript">
        require(
            [
                'jquery',
                'IWD_CartToQuote/js/helper/url',
                'IWD_CartToQuote/js/helper/base64'
            ],
            function($, urlHelper, base64) {
                $(document).ready(function () {
                    var iframeResize = function (event) {
                        var frame = document.getElementById('customerQuoteFrame');
                        if (frame && event.data.iwdC2QiFrameHeight) {
                            frame.style.height = event.data.iwdC2QiFrameHeight + "px";
                            $('#iwd_c2q_iframe_loader_wrapper').hide();
                        }
                    };

                    var changeUrl = function(event) {
                        if (event.data.iwdC2QiFramePage) {
                            var pathname = base64.encode(event.data.iwdC2QiFramePage);
                            var url = window.location.href;
                            url = urlHelper.setUrlParam(url, 'p', pathname);
                            if (window.location.href !== url) {
                                window.history.pushState('', '', url);
                            }
                        } else if (event.data.iwdC2QiFrameLoadPage) {
                            window.location.href = event.data.iwdC2QiFrameLoadPage;
                        }
                    };

                    if (window.addEventListener) {
                        window.addEventListener("message", iframeResize, false);
                        window.addEventListener("message", changeUrl, false);
                    } else if (window.attachEvent) {
                        window.attachEvent("onmessage", iframeResize);
                        window.attachEvent("onmessage", changeUrl);
                    }
                });
            }
        );
    </script>
<?php endif; ?>

