<?php
/**
 * @var $block \IWD\CartToQuote\Block\Adminhtml\System\Config\Renderer\Statuses
 */
?>
<?php
$statuses = $block->getStatuses();
$nativeStatuses = \IWD\CartToQuote\Model\Request\Status::getNativeStatuses();
?>
<div id="iwd_c2q_statuses_container" class="iwd_c2q_settings_container">
    <table>
        <thead>
        <tr>
            <td></td>
            <td><?php echo __('Name'); ?></td>
            <td><?php echo __('Function'); ?></td>
            <td><?php echo __('HEX Color'); ?></td>
            <td></td>
            <td></td>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($statuses as $status) { ?>
            <tr class="<?php if ($status['native']) { ?>iwd_c2q_native_settings<?php } ?> ">
                <td class="iwd_c2q_settings_sort" title="<?php echo __('Sort'); ?>">
                    <div class="iwd_c2q_settings_sort_icon"></div>
                </td>
                <td class="iwd_c2q_settings_name" title="<?php echo __('Name'); ?>">
                    <input value="<?php echo $status['id']; ?>"
                           name="iwd_c2q_statuses[<?php echo $status['id'] ?>][id]"
                           type="hidden"/>
                    <input type="text" class="required-entry"
                           placeholder="<?php echo __('Status name'); ?>"
                           title="<?php echo __('Status name'); ?>"
                           name="iwd_c2q_statuses[<?php echo $status['id'] ?>][name]"
                           value="<?php echo $status['name']; ?>"
                           readonly="readonly"
                    />
                    <input type="hidden"
                           value="<?php echo $status['native'] ?>"
                           name="iwd_c2q_statuses[<?php echo $status['id'] ?>][native]"/>
                </td>
                <td class="iwd_c2q_settings_function" title="<?php echo __('Function'); ?>">
                    <?php if ($status['native']) { ?>
                        <input type="hidden"
                               value="<?php echo $status['code'] ?>"
                               name="iwd_c2q_statuses[<?php echo $status['id'] ?>][code]"/>
                    <?php } ?>
                    <select
                        <?php if ($status['native']){ ?>disabled="disabled"<?php } else { ?>
                        name="iwd_c2q_statuses[<?php echo $status['id'] ?>][code]"
                    <?php } ?>
                        title="<?php echo __('Select status role'); ?>">
                        <?php foreach ($nativeStatuses as $key => $nativeStatus) { ?>
                            <option
                                <?php echo $status['code'] === $nativeStatus['code'] ? 'selected' : '' ?>
                                    value="<?php echo $nativeStatus['code'] ?>">
                                <?php echo $nativeStatus['name']; ?>
                            </option>
                        <?php } ?>
                    </select>
                </td>
                <td class="iwd_c2q_settings_color"
                    title="<?php echo __('Color'); ?>">
                    <input
                            type="text"
                            title="<?php echo __('Color'); ?>"
                            value="<?php echo $status['color']; ?>"
                            name="iwd_c2q_statuses[<?php echo $status['id'] ?>][color]"/>
                    <span style="background-color: #<?php echo $status['color']; ?>"></span>
                </td>
                <td class="iwd_c2q_settings_enable" title="<?php echo __('Enable/Disable'); ?>">
                    <div class="admin__actions-switch" data-role="switcher">
                        <input type="hidden"
                               value="<?php echo $status['enable']; ?>"
                               name="iwd_c2q_statuses[<?php echo $status['id'] ?>][enable]"/>
                        <input type="checkbox" class="admin__actions-switch-checkbox iwd_c2q_settings_custom_checkbox"
                               value="1"
                               <?php if ($status['native']) { ?>disabled="disabled"<?php } ?>
                               id="iwd_c2q_statuses_.<?php echo $status['id'] ?>._enable"
                            <?php echo((int)$status['enable'] ? 'checked="checked"' : ''); ?>/>
                        <label class="admin__actions-switch-label <?php if ($status['native']) { ?>disabled<?php } ?>"
                               for="iwd_c2q_statuses_.<?php echo $status['id'] ?>._enable">
                            <span class="admin__actions-switch-text"></span>
                        </label>
                    </div>
                </td>
                <td class="iwd_c2q_settings_delete" title="<?php echo __('Delete'); ?>">
                    <div class="iwd_c2q_settings_delete_icon"></div>
                    <input
                            value="0"
                            name="iwd_c2q_statuses[<?php echo $status['id'] ?>][is_deleted]"
                            type="hidden"/>
                </td>
            </tr>
        <?php } ?>
        </tbody>
        <tfoot>
        <?php /*   <tr>
            <td></td>
            <td colspan="5">
                <div class="iwd_c2q_settings_add_new">
                    <?php echo __('Add Status'); ?>
                </div>
            </td>
        </tr>
        <tr style="display: none;">
            <td class="iwd_c2q_settings_sort" title="<?php echo __('Sort'); ?>">
                <div class="iwd_c2q_settings_sort_icon"></div>
            </td>
            <td class="iwd_c2q_settings_name" title="<?php echo __('Name'); ?>">
                <input type="text" class="required-entry"
                       readonly="readonly"
                       placeholder="<?php echo __('Status name'); ?>"
                       title="<?php echo __('Status name'); ?>"
                       name="iwd_c2q_statuses[new][iwd_c2q_unique_id][name]"/>
                <input type="hidden"
                       value="0"
                       disabled="disabled"
                       name="iwd_c2q_statuses[new][iwd_c2q_unique_id][native]"/>
            </td>
            <td class="iwd_c2q_settings_function" title="<?php echo __('Function'); ?>">
                <select
                        name="iwd_c2q_statuses[new][iwd_c2q_unique_id][code]"
                        disabled="disabled"
                        title="<?php echo __('Select status role'); ?>">
                    <?php foreach ($nativeStatuses as $key => $nativeStatus) : ?>
                        <option value="<?php echo $nativeStatus['code'] ?>">
                            <?php echo $nativeStatus['name']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td class="iwd_c2q_settings_color" title="<?php echo __('Color'); ?>">
                <?php $nativeStatus = current($nativeStatuses); ?>
                <input
                        value="<?php echo $nativeStatus['color']; ?>"
                        type="text"
                        disabled="disabled"
                        title="<?php echo __('Color'); ?>"
                        name="iwd_c2q_statuses[new][iwd_c2q_unique_id][color]"/>
                <span style="background-color: #<?php echo $nativeStatus['color']; ?>"></span>
            </td>
            <td class="iwd_c2q_settings_enable" title="<?php echo __('Enable/Disable'); ?>">
                <div class="admin__actions-switch" data-role="switcher">
                    <input type="hidden"
                           value="1"
                           disabled="disabled"
                           name="iwd_c2q_statuses[new][iwd_c2q_unique_id][enable]"/>
                    <input type="checkbox" class="admin__actions-switch-checkbox iwd_c2q_settings_custom_checkbox"
                           value="1"
                           disabled="disabled"
                           checked="checked"/>
                    <label class="admin__actions-switch-label">
                        <span class="admin__actions-switch-text"></span>
                    </label>
                </div>
            </td>
            <td class="iwd_c2q_settings_delete" title="<?php echo __('Delete'); ?>">
                <div class="iwd_c2q_settings_delete_icon"></div>
                <input
                        value="0"
                        disabled="disabled"
                        name="iwd_c2q_statuses[new][iwd_c2q_unique_id][is_deleted]"
                        type="hidden"/>
            </td>
        </tr>
 */ ?>
        </tfoot>
    </table>
</div>

<script type="text/javascript">
    // <![CDATA[
    require([
            'jquery',
            'jquery/ui'
        ],
        function ($) {
            $(document).ready(function () {
                $('.iwd_c2q_settings_container').closest('td.value').css({
                    'padding-right': '0',
                    'width': '100%'
                }).prev().remove();

                $('.iwd_c2q_settings_container').closest('td.value').next().remove();

                $('.iwd_c2q_settings_container .iwd_c2q_settings_color input').each(function () {
                    var element = $(this);
                    element.ColorPicker({
                        color: $(this).next().val(),
                        onChange: function (hsb, hex, rgb) {
                            element.next().css('background-color', '#' + hex);
                            element.val(hex);
                        }
                    })
                });

                $('.iwd_c2q_settings_container tbody').sortable().sortable('enable');

                $(document).on('change', '.iwd_c2q_settings_container .iwd_c2q_settings_custom_checkbox', function () {
                    $(this).prev().val(+$(this).is(':checked'));
                });

                $(document).on('click', '.iwd_c2q_settings_container tr:not(.iwd_c2q_native_settings) .iwd_c2q_settings_delete_icon', function () {
                    $(this).next().val('1').closest('tr').remove();
                });

                $(document).on('click', '.iwd_c2q_settings_container .iwd_c2q_settings_add_new', function () {
                    var element = $(this).closest('tr').next().clone();
                    var randomId = Math.random().toString(36).substr(2, 5);

                    element.find('input, select').removeAttr('disabled').each(function () {
                        if ($(this).attr('name')) {
                            $(this).attr('name', $(this).attr('name').replace('iwd_c2q_unique_id', randomId));
                        }
                    });

                    $($(this).closest('tfoot').prev()).append(element).promise().done(function () {
                        element.show();

                        element.find('.iwd_c2q_settings_custom_checkbox').attr('id', randomId).next().attr('for', randomId);

                        $(element).find('.iwd_c2q_settings_color input').each(function () {
                            var element = $(this);
                            console.log('test--');

                            element.ColorPicker({
                                color: $(this).next().val(),
                                onChange: function (hsb, hex, rgb) {
                                    element.next().css('background-color', '#' + hex);
                                    element.val(hex);
                                }
                            })
                        });

                        $('.iwd_c2q_settings_container tbody').sortable().sortable('enable');
                    });
                });
            });
        }
    );
    // ]]>
</script>
