<?php
/**
 * @var $block \IWD\CartToQuote\Block\Widget\Fields\Gender
 */
?>
<div class="field gender<?php if ($block->isRequired()) echo ' required' ?>">
    <label class="label" title="<?php echo $block->getTitle() ?>" for="<?php echo $block->getHtmlId()?>">
        <span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span>
    </label>
    <div class="control">
        <select id="<?php /* @escapeNotVerified */ echo $block->getFieldId('gender')?>" name="<?php /* @escapeNotVerified */ echo $block->getFieldName('gender')?>" title="<?php /* @escapeNotVerified */ echo __('Gender') ?>"<?php if ($block->isRequired()):?> class="validate-select" data-validate="{required:true}"<?php endif; ?> <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?>>
            <?php $options = $block->getGenderOptions(); ?>
            <?php $value = $block->getGender();?>
            <?php foreach ($options as $option):?>
                <option value="<?php /* @escapeNotVerified */ echo $option->getValue() ?>"<?php if ($option->getValue() == $value) echo ' selected="selected"' ?>><?php /* @escapeNotVerified */ echo __($option->getLabel()) ?></option>
            <?php endforeach;?>
        </select>
    </div>
</div>
